---
version: '3.8'
services:
  ## BSC RPC Node - JSON-RPC Server to access the blockchain.
  bsc-rpc: # This is the bootstrap node
    image: bsc:local
    restart: always
    env_file: .env
    ports:
      - 8545:8545
      - 8546:8546
    depends_on:
      - netstats
    environment:
      NODE_ID: bsc-rpc
    volumes:
      - ./bsc/bsc-rpc:/home/docker/.ethereum
      - ./scripts:/scripts
      - ./config:/config
      - ./socket:/home/docker/socket
    command: ash /scripts/bsc-rpc.sh

  ## BSC Validator Node - Performs the block mining.
  bsc-validator1:
    image: bsc:local
    env_file: .env
    depends_on:
      - netstats
    environment:
      NODE_ID: bsc-validator
      BOOTSTRAP_HOST: bsc-rpc
    volumes:
      - ./bsc/bsc-validator1:/home/docker/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh

  ## Netstats Dashboard - Contains metrics about the blockchain.
  netstats:
    image: netstats:local
    restart: always
    ports:
      - 3000:3000
    environment:
      WS_SECRET: bscpwd
    logging:
        driver: none

  bsc-init:
    image: bsc-init:local
    depends_on:
      - bsc-rpc
    environment:
      # For some reason this doesn't work, have to use UNIX socket.
      # ADDRESS: http://bsc:8545
      ADDRESS: /socket/geth.ipc
      KEYSTORE_DIR: /etc/geth/accounts
      COINBASE_ADDR: 0x7fd60C817837dCFEFCa6D0A52A44980d12F70C59
    volumes:
      - ./accounts:/etc/geth/accounts
      - ./socket:/socket
volumes:
  tmp:
    driver: local
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 99.99.0.0/16
